server:
  servlet:
    contextPath: /api
  port: 8082
spring:
  datasource:
    continue-on-error: true
    initialization-mode: always
    initialize: true
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/validation
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    exchange: amq.direct
    validationqueue: validation-queue
    validationrouting: validation-routing-key
    responsequeue: validation-response-queue
    responserouting: validation-response-key
